routes/web.php
<?php

use App\Http\Controllers\Admin\ActionsController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\SpecializationsController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\Specialists;
use App\Http\Controllers\Controller;
use App\Http\Controllers\LoginController;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'language'], function () {
    Route::get('/', [Controller::class, 'main'])->name('main');
    Route::get('/specialists', [Controller::class, 'specialists'])->name('specialists');
    Route::get('/actions', [Controller::class, 'actions'])->name('actions');
    Route::get('/actions/{action}', [Controller::class, 'action'])->name('action');
    Route::get('/services', [Controller::class, 'services'])->name('services');
    Route::get('/services/{service}/{mode?}', [Controller::class, 'service'])->name('service');
    Route::get('/ajax/services/{specialization}', [Controller::class, 'ajaxSpecialization'])->name('services.ajax');

    Route::get('/contacts', [Controller::class, 'contacts'])->name('contacts');
    Route::post('/feedback', [Controller::class, 'feedback'])->name('feedback');
    Route::post('/record', [Controller::class, 'record'])->name('record');

    Route::get('/login', [LoginController::class, 'show'])->name('login');
    Route::post('/login', [LoginController::class, 'login'])->name('auth');
    Route::get('setlocale/{locale}', function($lang) {
        \Session::put('locale', $lang);

        return redirect()->back();
    })->name('setLocale');
});

Route::group(['middleware' => 'admin', 'prefix' => 'my-dashboard'], function() {
    Route::get('/', [AdminController::class, 'index'])->name('admin.index');
    Route::get('/orders/{type?}', [AdminController::class, 'orders'])->name('admin.orders');

    Route::get('/specialists', [Specialists::class, 'index'])->name('admin.specialists.index');
    Route::get('/specialists/delete/{doctor}', [Specialists::class, 'delete'])->name('admin.specialists.delete');
    Route::get('/specialists/create', [Specialists::class, 'create'])->name('admin.specialists.create');
    Route::post('/specialists/store', [Specialists::class, 'store'])->name('admin.specialists.store');
    Route::get('/specialists/edit/{doctor}', [Specialists::class, 'edit'])->name('admin.specialists.edit');
    Route::post('/specialists/update/{doctor}', [Specialists::class, 'update'])->name('admin.specialists.update');

    Route::get('/actions', [ActionsController::class, 'index'])->name('admin.actions.index');
    Route::get('/actions/create', [ActionsController::class, 'create'])->name('admin.actions.create');
    Route::get('/actions/delete/{action}', [ActionsController::class, 'delete'])->name('admin.actions.delete');
    Route::post('/actions/store', [ActionsController::class, 'store'])->name('admin.actions.store');
    Route::get('/actions/edit/{action}', [ActionsController::class, 'edit'])->name('admin.actions.edit');
    Route::post('/actions/update/{action}', [ActionsController::class, 'update'])->name('admin.actions.update');

    Route::get('/specializations', [SpecializationsController::class, 'index'])->name('admin.specializations.index');
    Route::get('/specializations/create', [SpecializationsController::class, 'create'])->name('admin.specializations.create');
    Route::get('/specializations/delete/{specialization}', [SpecializationsController::class, 'delete'])->name('admin.specializations.delete');
    Route::post('/specializations/store', [SpecializationsController::class, 'store'])->name('admin.specializations.store');
    Route::get('/specializations/edit/{specialization}', [SpecializationsController::class, 'edit'])->name('admin.specializations.edit');
    Route::post('/specializations/update/{specialization}', [SpecializationsController::class, 'update'])->name('admin.specializations.update');

    Route::get('/services', [ServicesController::class, 'index'])->name('admin.services.index');
    Route::get('/services/create', [ServicesController::class, 'create'])->name('admin.services.create');
    Route::get('/services/delete/{service}', [ServicesController::class, 'delete'])->name('admin.services.delete');
    Route::post('/services/store', [ServicesController::class, 'store'])->name('admin.services.store');
    Route::get('/services/edit/{service}', [ServicesController::class, 'edit'])->name('admin.services.edit');
    Route::post('/services/update/{service}', [ServicesController::class, 'update'])->name('admin.services.update');
});

app/Models/Services.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

/**
 * Class Services
 * @package App\Models
 * @method select
 */

class Services extends Model
{
    use AllCacheTrait;

    public $casts = [
        'doctors' => 'json',
    ];

    protected $guarded = ['id'];

    public function getTitleAttribute() {
        return $this->{'name_'.session('locale')};
    }

    public function getShortcutAttribute() {
        return $this->{'shortcut_'.session('locale')};
    }

    public function getDescriptionAttribute() {
        return $this->{'description_'.session('locale')};
    }
}

resources/views/_contacts.blade.php
<section class="contacts-block">
    <div class="contacts-block__title">{{ __('app.layout.menu.contacts') }}</div>
    <div class="contacts-block__subtitle">{{ __('app.welcome.our_specs.text') }}</div>
    <div class="contacts-block__list">
        <div class="contacts-block-item">
            <div class="contacts-block-item__header">
                <div class="contacts-block-item__address">г. Алматы</div>
                <div class="contacts-block-item__time">08:00 - 21:00</div>
            </div>
            <div class="contacts-block-item__bold">
                <div class="contacts-block-item__address">Мендикулова бульвар, 105</div>
                <div class="contacts-block-item__time">Пн - Вс</div>
            </div>
            <div class="contacts-block-item__header">Самал 2-й микрорайон, жилой комплекс Фантазия</div>
            <div class="contacts-block-item__phones">
                <div class="contacts-block-item__phone">
                    <img src="/images/content/phone.svg" alt=""/>
                    <span>+7 727 272-33-43</span>
                </div>
                <div class="contacts-block-item__phone">
                    <img src="/images/content/whatsapp-mini.svg" alt=""/>
                    <span>+7 727 272-33-43</span>
                </div>
                <div class="contacts-block-item__phone">
                    <img src="/images/content/telegram-mini.svg" alt=""/>
                    <span>+7 727 272-33-43</span>
                </div>
            </div>
        </div>
        <div class="contacts-block-item">
            <div class="contacts-block-item__header">
                <div class="contacts-block-item__address">г. Алматы</div>
                <div class="contacts-block-item__time">08:00 - 21:00</div>
            </div>
            <div class="contacts-block-item__bold">
                <div class="contacts-block-item__address">Мендикулова бульвар, 105</div>
                <div class="contacts-block-item__time">Пн - Вс</div>
            </div>
            <div class="contacts-block-item__header">Самал 2-й микрорайон, жилой комплекс Фантазия</div>
            <div class="contacts-block-item__phones">
                <div class="contacts-block-item__phone">
                    <img src="/images/content/phone.svg" alt=""/>
                    <span>+7 727 272-33-43</span>
                </div>
                <div class="contacts-block-item__phone">
                    <img src="/images/content/whatsapp-mini.svg" alt=""/>
                    <span>+7 727 272-33-43</span>
                </div>
                <div class="contacts-block-item__phone">
                    <img src="/images/content/telegram-mini.svg" alt=""/>
                    <span>+7 727 272-33-43</span>
                </div>
            </div>
        </div>
        <div class="contacts-block-item">
            <div class="contacts-block-item__header">
                <div class="contacts-block-item__address">г. Алматы</div>
                <div class="contacts-block-item__time">08:00 - 21:00</div>
            </div>
            <div class="contacts-block-item__bold">
                <div class="contacts-block-item__address">Мендикулова бульвар, 105</div>
                <div class="contacts-block-item__time">Пн - Вс</div>
            </div>
            <div class="contacts-block-item__header">Самал 2-й микрорайон, жилой комплекс Фантазия</div>
            <div class="contacts-block-item__phones">
                <div class="contacts-block-item__phone">
                    <img src="/images/content/phone.svg" alt=""/>
                    <span>+7 727 272-33-43</span>
                </div>
                <div class="contacts-block-item__phone">
                    <img src="/images/content/whatsapp-mini.svg" alt=""/>
                    <span>+7 727 272-33-43</span>
                </div>
                <div class="contacts-block-item__phone">
                    <img src="/images/content/telegram-mini.svg" alt=""/>
                    <span>+7 727 272-33-43</span>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="map-block">
    <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A71ffe894566d180fb7bb3c39a9adad12f1a77acd8df78c57fe9d8772184d55df&amp;width=100%25&amp;height=300&amp;lang=ru_RU&amp;scroll=true"></script>
</section>

resources/views/_layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Zamzam</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/css/app.css" rel="stylesheet">
    <script>
        window.lang = "{{ session('locale') }}";
    </script>
</head>
<body>
<header>
    <div class="header-top">
        <div class="header-top__slogan">{{ __('app.layout.title') }}</div>
        @if (session('locale') === 'ru')
            <div class="header-top__lang"><a href="{{ route('setLocale', ['locale' => 'kk']) }}">KK</a></div>
        @else
            <div class="header-top__lang"><a href="{{ route('setLocale', ['locale' => 'ru']) }}">RU</a></div>
        @endif
    </div>

    <div class="header-menu">
        <div class="menu-btn d-md-none d-lg-none d-xl-none"><img src="/images/content/menu.svg" alt=""/></div>
        <div class="header-menu__left">
            <div class="header-menu__logo">
                <a href="{{ route('main') }}"><img src="/images/content/logo.jpg" alt="logo"/></a>
            </div>
            <div class="header-menu__items">
                <div class="header-menu__item">
                    {{ __('app.layout.menu.about_us') }}
                </div>
                <div class="header-menu__item">
                    <a href="{{ route('services') }}">{{ __('app.layout.menu.services') }}</a>
                </div>
                <div class="header-menu__item">
                    <a href="{{ route('specialists') }}">{{ __('app.layout.menu.specialists') }}</a>
                </div>
                <div class="header-menu__item">
                    <a href="{{ route('actions') }}">{{ __('app.layout.menu.actions') }}</a>
                </div>
                <div class="header-menu__item">
                    <a href="{{ route('contacts') }}">{{ __('app.layout.menu.contacts') }}</a>
                </div>
            </div>
        </div>

        <div class="header-menu__right">
            <a href="#"><img src="/images/content/instagram.svg" alt="instagram"/></a>
            <a href="#"><img src="/images/content/whatsapp.svg" alt="whatsapp"/></a>
            <a href="#"><img src="/images/content/telegram.svg" alt="telegram"/></a>
            <a href="#"><img src="/images/content/youtube.svg" alt="youtube"/></a>
        </div>
    </div>

    <div class="header-menu-items d-none">
        <div class="header-menu__item">
            {{ __('app.layout.menu.about_us') }}
        </div>
        <div class="header-menu__item">
            {{ __('app.layout.menu.services') }}
        </div>
        <div class="header-menu__item">
            <a href="{{ route('specialists') }}">{{ __('app.layout.menu.specialists') }}</a>
        </div>
        <div class="header-menu__item">
            <a href="{{ route('actions') }}">{{ __('app.layout.menu.actions') }}</a>
        </div>
        <div class="header-menu__item">
            <a href="{{ route('contacts') }}">{{ __('app.layout.menu.contacts') }}</a>
        </div>
    </div>
</header>

@yield('content')

<footer>
    <div class="d-none d-md-flex">
        <div class="footer-column footer-column--first">
            <a href="{{ route('main') }}"><img src="/images/content/logo.jpg" alt=""/></a>
            <div class="footer-column__about">
                {{ __('app.layout.footer.title') }}
            </div>
            <div class="footer-column__sites">
                <a href="#"><img src="/images/content/instagram.svg" alt=""/></a>
                <a href="#"><img src="/images/content/whatsapp.svg" alt=""/></a>
                <a href="#"><img src="/images/content/telegram.svg" alt=""/></a>
                <a href="#"><img src="/images/content/youtube.svg" alt=""/></a>
            </div>
        </div>
        <div class="footer-column">
            <div class="footer-column__title">{{ __('app.layout.footer.about_us') }}</div>

            <div class="footer-column__link">{{ __('app.layout.menu.about_us') }}</div>
            <div class="footer-column__link">{{ __('app.layout.menu.services') }}</div>
            <div class="footer-column__link"><a href="{{ route('specialists') }}">{{ __('app.layout.menu.specialists') }}</a></div>
            <div class="footer-column__link"><a href="{{ route('actions') }}">{{ __('app.layout.menu.actions') }}</a></div>
            <div class="footer-column__link"><a href="{{ route('contacts') }}">{{ __('app.layout.menu.contacts') }}</a></div>
        </div>
        <div class="footer-column">
            <div class="footer-column__title">{{ __('app.layout.footer.pop_services') }}</div>

            <div class="footer-column__link">Карбункул</div>
            <div class="footer-column__link">Роды в родильном доме Рахат</div>
            <div class="footer-column__link">Хеликобактер пилори</div>
            <div class="footer-column__link">Вросший ноготь</div>
        </div>
        <div class="footer-column footer-column--offset">
            <div class="footer-column__link">Карбункул</div>
            <div class="footer-column__link">Роды в родильном доме Рахат</div>
            <div class="footer-column__link">Хеликобактер пилори</div>
            <div class="footer-column__link">Вросший ноготь</div>
        </div>
        <div class="footer-column footer-column--offset">
            <div class="footer-column__link">Карбункул</div>
            <div class="footer-column__link">Роды в родильном доме Рахат</div>
            <div class="footer-column__link">Хеликобактер пилори</div>
            <div class="footer-column__link">Вросший ноготь</div>
        </div>
        <div class="footer-column">
            <div class="footer-column__title">{{ __('app.layout.menu.contacts') }}</div>

            <div class="footer-column__link">+7 727 3999404</div>
            <div class="footer-column__link">+7 727 3999404</div>
            <div class="footer-column__link">+7 727 3999404</div>
            <div class="footer-column__address">г.Алматы, Мендикулова бульвар, 105</div>
            <div class="footer-column__address">Info@zamzam-med.kz</div>
        </div>
    </div>
    <div class="d-md-none d-lg-none d-xl-none d-flex">
        <div class="footer-column">
            <div class="footer-column__title">{{ __('app.layout.footer.about_us') }}</div>

            <div class="footer-column__link">{{ __('app.layout.menu.about_us') }}</div>
            <div class="footer-column__link">{{ __('app.layout.menu.services') }}</div>
            <div class="footer-column__link"><a href="{{ route('specialists') }}">{{ __('app.layout.menu.specialists') }}</a></div>
            <div class="footer-column__link"><a href="{{ route('actions') }}">{{ __('app.layout.menu.actions') }}</a></div>
            <div class="footer-column__link"><a href="{{ route('contacts') }}">{{ __('app.layout.menu.contacts') }}</a></div>
        </div>
        <div class="footer-column">
            <div class="footer-column__title">{{ __('app.layout.menu.contacts') }}</div>

            <div class="footer-column__link">+7 727 3999404</div>
            <div class="footer-column__link">+7 727 3999404</div>
            <div class="footer-column__link">+7 727 3999404</div>
            <div class="footer-column__address">г.Алматы, Мендикулова бульвар, 105</div>
            <div class="footer-column__address">Info@zamzam-med.kz</div>
        </div>
    </div>
    <div class="d-md-none d-lg-none d-xl-none d-flex flex-column align-items-baseline">
        <a href="{{ route('main') }}"><img src="/images/content/logo.jpg" alt=""/></a>
        <div class="footer-column__about">
            {{ __('app.layout.footer.title') }}
        </div>
        <div class="footer-column__sites">
            <a href="#"><img src="/images/content/instagram.svg" alt=""/></a>
            <a href="#"><img src="/images/content/whatsapp.svg" alt=""/></a>
            <a href="#"><img src="/images/content/telegram.svg" alt=""/></a>
            <a href="#"><img src="/images/content/youtube.svg" alt=""/></a>
        </div>
    </div>
</footer>

<section class="copyright-block">
    <div>© Copyright 2016 - 2020 Zamzam. All Rights Reserved.</div>
</section>

<script src="https://www.google.com/recaptcha/api.js"></script>
<script type="application/javascript" src="/js/app.js"></script>
</body>
</html>

resources/views/_modal-report.blade.php
<div class="modal-component__title">Онлайн заявка</div>
<div class="modal-component__subtitle">Заполните форму и мы подберем для Вас удобное время и условия!</div>
<form class="modal-component__form" method="post" action="{{ route('record') }}" id="request-form">
    {{ csrf_field() }}
    <div class="row">
        <div class="col-6 col-md-6">
            <input type="text" placeholder="Введите ваше имя" class="modal-component__input" name="username" required/>
        </div>
        <div class="col-6 col-md-6">
            <input type="text" placeholder="Введите ваш номер: +7 (- - -) - - -  - -  - -" class="modal-component__input" name="userphone" required/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <textarea placeholder="Введите ваш комментарий" class="modal-component__textarea" name="comment"></textarea>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9 col-8 modal-component__hint">
            Заполняя данную форму, Вы соглашаетесь c условиями обработки персональных данных. Мы гарантируем конфиденциальность Вашего обращения!
        </div>
        <div class="col-md-3 col-4">
            <button class="modal-component__button g-recaptcha"
                    data-sitekey="6LfHMlcaAAAAAG7t04y5o30DYh98CbSKhpknpbUn"
                    data-callback='requestForm'
                    data-action='submit'>Записаться к врачу</button>
        </div>
    </div>
</form>

resources/views/action.blade.php
@extends('_layout')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('main') }}">{{ __('app.layout.menu.main') }}</a></li>
            <li class="breadcrumb-item"><a href="{{ route('actions') }}">{{ __('app.layout.menu.actions') }}</a></li>
            <li class="breadcrumb-item active">{{ $action->name }}</li>
        </ol>
    </nav>

    <div class="actions-page">
        <div class="actions-page__title">{{ $action->name }}</div>
        <img src="{{ $action->cover }}" alt="" class="mb-3"/>
        <div class="">
            <div class="actions-content">
                <div class="actions-content__title">{{ $action->name }}</div>
                <div class="actions-content__text">{!! $action->text !!}</div>
            </div>
        </div>
    </div>

    <div class="report-form">
        <div class="report-form__wrapper">
            @include('_modal-report')
        </div>
    </div>
    @include('_contacts')
@endsection

resources/views/actions.blade.php
@extends('_layout')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('main') }}">{{ __('app.layout.menu.main') }}</a></li>
            <li class="breadcrumb-item active">{{ __('app.layout.menu.actions') }}</li>
        </ol>
    </nav>

    <div class="actions-page">
        <div class="actions-page__title">{{ __('app.layout.menu.actions') }}</div>
        <div class="">
            <div class="actions-content">
                <div class="actions-content__title">{{ __('app.actions.subtitle') }}</div>
                <div class="actions-content__text">{!! __('app.actions.text') !!}</div>
                <div class="actions-content__list">
                    @foreach($actions as $action)
                        <div class="actions-item">
                            <div class="actions-item__about">
                                <div class="actions-item__title">{{ $action->name }}</div>
                                <div class="actions-item__link"><a href="{{ route('action', ['action' => $action->id]) }}">{{ __('app.actions.btn') }}</a></div>
                            </div>
                            <div class="actions-item__image">
                                <img src="{{ $action->preview }}" alt=""/>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contacts.blade.php
@extends('_layout')

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('main') }}">{{ __('app.layout.menu.main') }}</a></li>
            <li class="breadcrumb-item active">{{ __('app.layout.menu.contacts') }}</li>
        </ol>
    </nav>

    @include('_contacts')
@endsection

resources/views/login.blade.php
@extends('_layout')

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('main') }}">{{ __('app.layout.menu.main') }}</a></li>
            <li class="breadcrumb-item active">Логин</li>
        </ol>
    </nav>

    <section class="services-block" style="max-width: 400px">
        <div class="services-block__title">Login</div>
        <div class="services-block__subtitle">{{ __('app.welcome.services.text') }}</div>
        <form method="post" action="{{ route('auth') }}">
            <input class="form-control" name="key" type="password"/>
            <button class="form-control btn-outline-primary">Login</button>
            {{ csrf_field() }}
        </form>
    </section>
@endsection

resources/views/service.blade.php
@extends('_layout')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('main') }}">{{ __('app.layout.menu.main') }}</a></li>
            <li class="breadcrumb-item"><a href="{{ route('actions') }}">{{ __('app.layout.menu.services') }}</a></li>
            <li class="breadcrumb-item active">{{ $service->title }}</li>
        </ol>
    </nav>

    <div class="actions-page">
        <div class="actions-page__title">{{ __('app.layout.menu.services') }}</div>
        <div class="">
            <div class="actions-content">
                <div class="actions-content__title">{{ $service->title }}</div>
                <div class="actions-content__text">{!! $service->shortcut !!}</div>
                <div class="actions-content__tabs">
                    <a class="actions-content__tab @if ($mode === 'description') actions-content__tab--selected @endif" href="{{ route('service', ['service' => $service, 'mode' => 'description']) }}">Описание</a>
                    <a class="actions-content__tab @if ($mode === 'doctors') actions-content__tab--selected @endif" href="{{ route('service', ['service' => $service, 'mode' => 'doctors']) }}">Врачи</a>
                </div>

                @if ($mode === 'description')
                    <div class="actions-content__text mt-2">{!! $service->description !!}</div>
                @elseif ($mode === 'doctors')
                    <div class="specialists-list mt-2">
                        <div class="specialists-list__wrapper">
                            @foreach($service->doctors as $doctor)
                                <div class="our-specs-item">
                                    <img src="{{ $doctor['image'] }}" alt=""/>
                                    <div class="our-specs-item__name">{{ $doctor['name'] }}</div>
                                    <div class="our-specs-item__about">{{ $doctor['title'] }}</div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/services.blade.php
@extends('_layout')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('main') }}">{{ __('app.layout.menu.main') }}</a></li>
            <li class="breadcrumb-item active">{{ __('app.layout.menu.services') }}</li>
        </ol>
    </nav>

    <div class="actions-page">
        <div class="actions-page__title">{{ __('app.layout.menu.services') }}</div>
        <div class="">
            <div class="actions-content">
                <div class="actions-content__title">{{ __('app.actions.subtitle') }}</div>
                <div class="actions-content__text">{!! __('app.actions.text') !!}</div>
                <div class="actions-content__list">
                    @foreach($specializations as $specialization)
                        <div class="actions-item">
                            <div class="actions-item__about">
                                <div class="actions-item__title">{{ $specialization->title }}</div>
                                <div class="actions-item__info d-none" id="info-specialization-{{ $specialization->id }}">
                                    <div class="actions-item__description">{{ $specialization->description }}</div>
                                    <div class="actions-item__services" id="services-specialization-{{ $specialization->id }}">

                                    </div>
                                </div>

                                <div class="actions-item__link js-show-specialization" id="show-specialization-{{ $specialization->id }}" data-specialization="{{ $specialization->id }}">
                                    {{ __('app.actions.btn') }}
                                </div>

                                <div class="actions-item__link js-hide-specialization d-none" id="hide-specialization-{{ $specialization->id }}" data-specialization="{{ $specialization->id }}">
                                    {{ __('app.actions.closeBtn') }}
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/specialists.blade.php
@extends('_layout')

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('main') }}">{{ __('app.layout.menu.main') }}</a></li>
            <li class="breadcrumb-item active">{{ __('app.layout.menu.specialists') }}</li>
        </ol>
    </nav>

    <div class="specialists-page">
        <div class="specialists-page__title">{{ __('app.layout.menu.specialists') }}</div>

        <form class="specialists-filter">
            <select class="specialists-dropdown specialists-dropdown--cities">
                <option name="almaty">Алматы</option>
            </select>

            <select class="specialists-dropdown specialists-dropdown--clinics">
                <option name="">Клиника</option>
            </select>

            <select class="specialists-dropdown specialists-dropdown--specialization" name="specialization_id">
                <option value="">{{ __('app.layout.menu.specialists') }}</option>
                @foreach($specializations as $specialization)
                    <option value="{{ $specialization->id }}" {{ $search['specialization'] === $specialization->id ? 'selected' : '' }}>
                        {{ $specialization->name }}
                    </option>
                @endforeach
            </select>

            <div class="specialists-search-input">
                <img src="/images/content/zoom-in.svg" alt="" class="specialists-search-input__icon"/>
                <input class="specialists-input" placeholder="{{ __('app.specialists.input_search') }}"/>
            </div>

            <button class="specialists-button">{{ __('app.specialists.button_search') }}</button>
        </form>

        @foreach($specializations as $specialization)
            @if (empty($specialization['doctors']))
                @continue
            @endif
            <div class="specialists-list">
                <div class="specialists-list__title">{{ $specialization->name }}</div>
                <div class="specialists-list__wrapper">
                    @foreach($specialization['doctors'] as $doctor)
                        <div class="our-specs-item">
                            <img src="{{ $doctor->image }}" alt=""/>
                            <div class="our-specs-item__name">{{ $doctor->name }}</div>
                            <div class="our-specs-item__about">{{ $doctor->title }}</div>
                        </div>
                    @endforeach
                </div>
            </div>
        @endforeach
    </div>

@endsection